### ISSUE TITLE
Compiler doesn't work

### ISSUE THREAD

**Issue by stevestavropoulos** [hiukim/mind-ar-js-doc#1]
On https://hiukim.github.io/mind-ar-js-doc/tools/compile/ when selecting any number of target images and pressing "Start", a black window appears and the following error in the console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at VM579 ff814c57.4b80e031.js:1
...
```
reffering to this:
```
function(){return t[c].imageList.map((function(e,t){return t}))})
```

Also, on page load the following is output on the console:
```
Uncaught Error: Dropzone already attached.
    at new b (dropzone.min.js:1)
    at dropzone.min.js:1
    at Function.Dropzone.discover (dropzone.min.js:1)
    at Dropzone._autoDiscoverFunction (dropzone.min.js:1)
    at HTMLDocument.i (dropzone.min.js:1)
```

**Comment by arky** [comment]
@stevestavropoulos Perhaps you could try filing this in mind-ar-js issue tracker? https://github.com/hiukim/mind-ar-js/issues/

**Comment by stevestavropoulos** [comment]
It was broken for a week or a little more as I remember, but then it got fixed. I guess nobody saw this report, but it got fixed nonetheless...
