### ISSUE TITLE
Image tracking - 3d Model wiggles a lot

### ISSUE THREAD

**Issue by mslitto** [hiukim/mind-ar-js-doc#2]
Hi I just follow your udemy course and managed to get an 3D model into the scene and add it to the anchor. It works, but the model wiggles a lot,... seems like it is not tracking the image properly. 
Do I miss here sth?

**Comment by arky** [comment]
@mslitto Perhaps you could file this issue in the correct mind-ar-js issue tracker https://github.com/hiukim/mind-ar-js/issues/

**Comment by mslitto** [comment]
thx I fixed it: 
```
const mindarConfig = {
    container: document.querySelector("#container"),
    filterMinCF: 0.00001,
    filterBeta: 0.01,
    warmupTolerance: 1,
    missTolerance: 3,
    imageTargetSrc: "mind/2_targets_new.mind",
}
```

**Comment by arky** [comment]
Great @mslitto You can then close this issue as resolved.
