### ISSUE TITLE
Anchor point position link broken

### ISSUE THREAD

**Issue by etekweb** [hiukim/mind-ar-js-doc#6]
The link [https://github.com/tensorflow/tfjs-models/blob/master/facemesh/mesh_map.jpg](https://github.com/tensorflow/tfjs-models/blob/master/facemesh/mesh_map.jpg) no longer goes anywhere.

This broken link can be found here:

- File location: docs/face-tracking-quick-start/webpage.md ([GitHub](https://github.com/hiukim/mind-ar-js-doc/blob/master/docs/face-tracking-quick-start/webpage.md))
- Live site: [https://hiukim.github.io/mind-ar-js-doc/face-tracking-quick-start/webpage#anchor-points](https://hiukim.github.io/mind-ar-js-doc/face-tracking-quick-start/webpage#anchor-points)

**Comment by etekweb** [comment]
I found a reference to the original filename [elsewhere online](https://github.com/spite/FaceMeshFaceGeometry/blob/master/assets/mesh_map.jpg), and it appears to be the same as the one used in the FaceMesh demo under the Three.js examples. Perhaps that file can be referenced instead?

**Comment by hiukim** [comment]
thx, thanks for reporting!
