### ISSUE TITLE
Virtual TryOn demo still has offset with face-tracking

### ISSUE THREAD

**Issue by FireDragonGameStudio** [hiukim/mind-ar-js-doc#8]
Hi,
unfortunately the sample at https://hiukim.github.io/mind-ar-js-doc/face-tracking-samples/tryon.html doesn't work properly on my Chrome with Pixel 5. My guess would be that the solution applied here - https://github.com/hiukim/mind-ar-js/issues/316 wasn't applied to the sample code.

best regards :)

**Comment by SachinGanesh** [comment]
Facing the same issue. Any update on this?

**Comment by marcusx2** [comment]
I'm guessing [this fix](https://github.com/hiukim/mind-ar-js/issues/316) didn't work. I also have the same problem.
